# Generated by Django 4.0.4 on 2022-06-23 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('annotateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('phrase', models.TextField()),
                ('phrase_normalised', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotateapp.document')),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_engine',
            field=models.CharField(default=datetime.datetime(2022, 6, 23, 15, 55, 15, 946050), help_text='Choose a RuleEngine class to execute this rule', max_length=512),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='RegexRule',
            new_name='Regex',
        ),
        migrations.DeleteModel(
            name='DocumentRegexRule',
        ),
        migrations.AddField(
            model_name='documentlabel',
            name='regex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotateapp.regex'),
        ),
    ]
